cc_library(
    name = "MmServicesImpl",
    srcs = [
        "ZMmService.cpp",
    ],
    hdrs = [
        "ZMmService.h",
    ],
    visibility = ["//src/cpp:__subpackages__"],
    deps = [
        "//src/cpp/mm:Mm",
        "//src/interface:cc_interfaces",
    ],
)
